
package srinivas.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ManageSurveyService", targetNamespace = "http://SOAP.srinivas/", wsdlLocation = "http://ec2-34-238-116-176.compute-1.amazonaws.com/Trial11/SearchData?wsdl")
public class ManageSurveyService
    extends Service
{

    private final static URL MANAGESURVEYSERVICE_WSDL_LOCATION;
    private final static WebServiceException MANAGESURVEYSERVICE_EXCEPTION;
    private final static QName MANAGESURVEYSERVICE_QNAME = new QName("http://SOAP.srinivas/", "ManageSurveyService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ec2-34-238-116-176.compute-1.amazonaws.com/Trial11/SearchData?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANAGESURVEYSERVICE_WSDL_LOCATION = url;
        MANAGESURVEYSERVICE_EXCEPTION = e;
    }

    public ManageSurveyService() {
        super(__getWsdlLocation(), MANAGESURVEYSERVICE_QNAME);
    }

    public ManageSurveyService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANAGESURVEYSERVICE_QNAME, features);
    }

    public ManageSurveyService(URL wsdlLocation) {
        super(wsdlLocation, MANAGESURVEYSERVICE_QNAME);
    }

    public ManageSurveyService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANAGESURVEYSERVICE_QNAME, features);
    }

    public ManageSurveyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManageSurveyService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SearchInterface
     */
    @WebEndpoint(name = "ManageSurveyPort")
    public SearchInterface getManageSurveyPort() {
        return super.getPort(new QName("http://SOAP.srinivas/", "ManageSurveyPort"), SearchInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchInterface
     */
    @WebEndpoint(name = "ManageSurveyPort")
    public SearchInterface getManageSurveyPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://SOAP.srinivas/", "ManageSurveyPort"), SearchInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANAGESURVEYSERVICE_EXCEPTION!= null) {
            throw MANAGESURVEYSERVICE_EXCEPTION;
        }
        return MANAGESURVEYSERVICE_WSDL_LOCATION;
    }

}
